# Generated by Django 4.2.4 on 2024-05-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_hotelroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroom',
            name='room_type',
            field=models.CharField(choices=[('St', 'Standard'), ('De', 'Deluxe'), ('Su', 'Suite')], max_length=20),
        ),
    ]
